### ISSUE TITLE
Не фармит после обновы

### ISSUE THREAD

**Issue by Nord1cWarr1or** [A-KTO-Tbl/1win#1]
Похоже что у них вышла обнова, и теперь у меня бот просто авторизуется и ничего не делает.

**Comment by A-KTO-Tbl** [comment]
Скоро реализую обнову в таком случае

**Comment by Stelfelics** [comment]
у меня работает, но, только что вышла обнова с каким-то крипто котом которого надо прокачивать

**Comment by A-KTO-Tbl** [comment]
> у меня работает, но, только что вышла обнова с каким-то крипто котом которого надо прокачивать

В любом случае придётся обновлять)

**Comment by lostfilm1989** [comment]
грузит проц и озу 200 мб

**Comment by Serjio85** [comment]
будет обнова или нет?

**Comment by oleks-kr** [comment]
> будет обнова или нет?

по ходу не скоро

**Comment by Imaroubat** [comment]
> Скоро реализую обнову в таком случае

когда ?

**Comment by Stelfelics** [comment]
> > у меня работает, но, только что вышла обнова с каким-то крипто котом которого надо прокачивать
> 
> В любом случае придётся обновлять)

братское сердце, подскажи, как ты отслеживаешь запросы с тг бота на сервак? запрос (ссылка) + заголовки? есть бот по червяку, но он навернулся и я хотел бы пофиксить.. он детектит что я с пк сижу.. пробовал менять UA на андроид 12, режим инкогнито, менять заголовки, но до сих пор детектит.. буду очень благодарен🥺👉👈

**Comment by A-KTO-Tbl** [comment]
Все кто ожидают обновления:

Сейчас доделаю стабильную версию для скрипта Blum, как только та версия станет стабильной, я сразу же применю все те изменения и для остальных скриптов

**Comment by A-KTO-Tbl** [comment]
> братское сердце, подскажи, как ты отслеживаешь запросы с тг бота на сервак?

Провожу снифинг с помощью приложения Reqable на андроид. Но софт кроссплатформенный

**Comment by Stelfelics** [comment]
> > братское сердце, подскажи, как ты отслеживаешь запросы с тг бота на сервак?
> 
> Провожу снифинг с помощью приложения Reqable на андроид. Но софт кроссплатформенный

ты мой герой!! великодушное спасибо!!!

**Comment by Stelfelics** [comment]
> > братское сердце, подскажи, как ты отслеживаешь запросы с тг бота на сервак?
> 
> Провожу снифинг с помощью приложения Reqable на андроид. Но софт кроссплатформенный

братик, я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее):
(заодно немного корректировки твоего гайда по получению tgWebAppData: заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)

**Comment by Imaroubat** [comment]
> Похоже что у них вышла обнова, и теперь у меня бот просто авторизуется и ничего не делает.

получи новую ссылку через запуск через /start в которой будет Query ID без него бот просто стоит авторизованный

**Comment by Nord1cWarr1or** [comment]
> > Похоже что у них вышла обнова, и теперь у меня бот просто авторизуется и ничего не делает.
> 
> получи новую ссылку через запуск через /start в которой будет Query ID без него бот просто стоит авторизованный

спасибо, помогло.
