### ISSUE TITLE
Очередная обнова | Ошибка инициализации

### ISSUE THREAD

**Issue by Nord1cWarr1or** [A-KTO-Tbl/1win#3]
![изображение](https://github.com/user-attachments/assets/451d8662-dcc5-465b-b364-42aa413a0979)

Как минимум сменился домен на https://cryptocklicker-frontend-rnd-prod.100hp.app/
Попытался заменить домен в скрпите, но проблему это не решило, а на этом мои полномочия всё...

**Comment by A-KTO-Tbl** [comment]
Обнова для 1win уже готовится. Ожидай

**Comment by lostfilm1989** [comment]
> Обнова для 1win уже готовится. Ожидай

спасибо

**Comment by A-KTO-Tbl** [comment]
Обнова готова!

**Comment by Nord1cWarr1or** [comment]
Решено, спасибо.
